# T3-Exercise-1: Tensor Fundamentals

---

## 🎯 LEARNING OBJECTIVES

- Understand what tensors are and why they're fundamental to neural networks
- Create different types of tensors (scalars, vectors, matrices, higher-dimensional)
- Master tensor properties: shape, rank, dtype, and size
- Apply basic tensor manipulations like reshaping and type conversion

## 🔗 CONNECTION TO NEURAL NETWORKS
Think of tensors as the "language" of neural networks:
- **Input data** (images, text) → Tensors
- **Weights and biases** → Tensors  
- **Activations and outputs** → Tensors
- **All mathematical operations** happen on tensors

**Real Example:** A 28×28 grayscale image becomes a tensor of shape (28, 28, 1).  
When we flatten it for a neural network, it becomes shape (784,)

In [24]:
# imports for this exercise
import tensorflow as tf
import numpy as np
import sys


In [25]:
# Environment verification
print("🔧 ENVIRONMENT CHECK")
print("=" * 30)
print(f"✅ TensorFlow version: {tf.__version__}")
print(f"✅ NumPy version: {np.__version__}")
print(f"✅ Python version: {sys.version.split()[0]}")


🔧 ENVIRONMENT CHECK
✅ TensorFlow version: 2.19.0
✅ NumPy version: 2.0.2
✅ Python version: 3.12.11


In [26]:
# Check if GPU is available (informational only)
if tf.config.list_physical_devices('GPU'):
    print("🚀 GPU acceleration available")
else:
    print("💻 Running on CPU (perfectly fine for learning)")

print("\n🎉 Environment ready!\n")

💻 Running on CPU (perfectly fine for learning)

🎉 Environment ready!



## 🧠 CORE CONCEPTS: What Are Tensors?

### SIMPLE EXPLANATION:
A tensor is just a container for numbers, but organized in a specific way:

- **Scalar (0D tensor):** Just one number → `42`
- **Vector (1D tensor):** A list of numbers → `[1, 2, 3]`  
- **Matrix (2D tensor):** A table of numbers → `[[1, 2], [3, 4]]`
- **3D+ tensors:** Multiple matrices stacked together

### NEURAL NETWORK ANALOGY:
- **Scalar:** A single pixel intensity
- **Vector:** A row of pixels, or neuron activations in a layer
- **Matrix:** An entire grayscale image, or layer weights
- **3D tensor:** Color image (height × width × channels)
- **4D tensor:** Batch of color images (batch × height × width × channels)

### WHY TENSORS MATTER:
1. **Efficient computation** (vectorization)
2. **GPU acceleration**
3. **Automatic differentiation** (backpropagation)
4. **Consistent interface** for all data types

##  STEP 1: Creating Different Types of Tensors
Let's create tensors step by step and understand each one

In [27]:
# Creating a SCALAR tensor (0D - just one number)
print("Creating a SCALAR tensor (0D - just one number):")
scalar = tf.constant(42)
print(f"Scalar tensor: {scalar}")


Creating a SCALAR tensor (0D - just one number):
Scalar tensor: 42


In [28]:
print(f"Value: {scalar.numpy()}")


Value: 42


In [30]:
print(f"This represents: A single value (like one pixel intensity)")


This represents: A single value (like one pixel intensity)


In [31]:
# Creating a VECTOR tensor (1D - list of numbers)
print("Creating a VECTOR tensor (1D - list of numbers):")
vector = tf.constant([1, 2, 3, 4, 5])
print(f"Vector tensor: {vector}")


Creating a VECTOR tensor (1D - list of numbers):
Vector tensor: [1 2 3 4 5]


In [33]:
print(f"Values: {vector.numpy()}")
print(f"This represents: One row of pixels, or activations from 5 neurons")


Values: [1 2 3 4 5]
This represents: One row of pixels, or activations from 5 neurons


In [34]:
# Creating a MATRIX tensor (2D - table of numbers)
print("Creating a MATRIX tensor (2D - table of numbers):")
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print(f"Matrix tensor:\n{matrix}")


Creating a MATRIX tensor (2D - table of numbers):
Matrix tensor:
[[1 2 3]
 [4 5 6]]


In [35]:
print(f"Values:\n{matrix.numpy()}")
print(f"This represents: A small grayscale image patch (2×3 pixels)")
print()

Values:
[[1 2 3]
 [4 5 6]]
This represents: A small grayscale image patch (2×3 pixels)



In [39]:
# Creating a 3D tensor (like a color image)
print("Creating a 3D tensor (like a color image):")
tensor_3d = tf.constant([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])
print(f"3D tensor:\n{tensor_3d}")


Creating a 3D tensor (like a color image):
3D tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## STEP 2: Understanding Tensor Properties
Let's examine each tensor's properties to understand what they mean

In [40]:
# Let's examine each tensor's properties
tensors_to_examine = [
    ("Scalar", scalar, "Single number"),
    ("Vector", vector, "List of 5 numbers"),
    ("Matrix", matrix, "2×3 table"),
    ("3D Tensor", tensor_3d, "2×2×2 cube")
]


In [41]:

for name, tensor, description in tensors_to_examine:
    print(f"\n🔍 Examining {name} ({description}):")
    print(f"  📏 Shape: {tensor.shape} ← Dimensions of the tensor")
    print(f"  📊 Rank: {tf.rank(tensor).numpy()} ← Number of dimensions")
    print(f"  🏷️  Data type: {tensor.dtype} ← Type of numbers stored")
    print(f"  📦 Total size: {tf.size(tensor).numpy()} ← Total number of elements")

    # Help students understand what shape means
    if tensor.shape.ndims == 0:
        print("     Shape () means: No dimensions, just one value")
    elif tensor.shape.ndims == 1:
        print(f"     Shape ({tensor.shape[0]},) means: {tensor.shape[0]} elements in a line")
    elif tensor.shape.ndims == 2:
        print(f"     Shape ({tensor.shape[0]}, {tensor.shape[1]}) means: {tensor.shape[0]} rows, {tensor.shape[1]} columns")
    elif tensor.shape.ndims == 3:
        print(f"     Shape ({tensor.shape[0]}, {tensor.shape[1]}, {tensor.shape[2]}) means: {tensor.shape[0]} matrices of {tensor.shape[1]}×{tensor.shape[2]}")


🔍 Examining Scalar (Single number):
  📏 Shape: () ← Dimensions of the tensor
  📊 Rank: 0 ← Number of dimensions
  🏷️  Data type: <dtype: 'int32'> ← Type of numbers stored
  📦 Total size: 1 ← Total number of elements
     Shape () means: No dimensions, just one value

🔍 Examining Vector (List of 5 numbers):
  📏 Shape: (5,) ← Dimensions of the tensor
  📊 Rank: 1 ← Number of dimensions
  🏷️  Data type: <dtype: 'int32'> ← Type of numbers stored
  📦 Total size: 5 ← Total number of elements
     Shape (5,) means: 5 elements in a line

🔍 Examining Matrix (2×3 table):
  📏 Shape: (2, 3) ← Dimensions of the tensor
  📊 Rank: 2 ← Number of dimensions
  🏷️  Data type: <dtype: 'int32'> ← Type of numbers stored
  📦 Total size: 6 ← Total number of elements
     Shape (2, 3) means: 2 rows, 3 columns

🔍 Examining 3D Tensor (2×2×2 cube):
  📏 Shape: (2, 2, 2) ← Dimensions of the tensor
  📊 Rank: 3 ← Number of dimensions
  🏷️  Data type: <dtype: 'int32'> ← Type of numbers stored
  📦 Total size: 8 ← Total 

##  STEP 3: Special Ways to Create Tensors
Neural networks often need tensors with specific patterns

In [14]:
# Creating tensors filled with ZEROS (common for initializing bias)
print("Creating tensors filled with ZEROS (common for initializing bias):")
zeros_matrix = tf.zeros((3, 4))
print(f"3×4 matrix of zeros:\n{zeros_matrix}")
print("💡 Use case: Initializing bias vectors in neural networks")
print()

Creating tensors filled with ZEROS (common for initializing bias):
3×4 matrix of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
💡 Use case: Initializing bias vectors in neural networks



In [ ]:
# Creating tensors filled with ZEROS (common for initializing bias)
print("Creating tensors filled with ZEROS (common for initializing bias):")
zeros_matrix = tf.zeros((3, 4))
print(f"3×4 matrix of zeros:\n{zeros_matrix}")
print("💡 Use case: Initializing bias vectors in neural networks")
print()

In [15]:
# Creating tensors filled with ONES
print("Creating tensors filled with ONES:")
ones_vector = tf.ones(5)
print(f"Vector of 5 ones: {ones_vector}")
print("💡 Use case: Creating masks or initialization")
print()

Creating tensors filled with ONES:
Vector of 5 ones: [1. 1. 1. 1. 1.]
💡 Use case: Creating masks or initialization



In [16]:
# Creating tensors with RANDOM values (crucial for neural networks)
print("Creating tensors with RANDOM values (crucial for neural networks):")
random_matrix = tf.random.normal((2, 3), mean=0.0, stddev=1.0)
print(f"2×3 matrix with random normal values:\n{random_matrix}")
print("💡 Use case: Initializing weights in neural networks")
print()

Creating tensors with RANDOM values (crucial for neural networks):
2×3 matrix with random normal values:
[[ 0.73941964  0.07404348 -0.444484  ]
 [-0.42385274 -1.0913789  -0.06087291]]
💡 Use case: Initializing weights in neural networks



In [17]:
# Creating a VARIABLE tensor (weights that can be trained)
print("Creating a VARIABLE tensor (weights that can be trained):")
trainable_weights = tf.Variable(tf.random.normal((2, 3), stddev=0.1), name="layer_weights")
print(f"Trainable weights:\n{trainable_weights}")
print("💡 Use case: Neural network weights that update during training")
print()

Creating a VARIABLE tensor (weights that can be trained):
Trainable weights:
<tf.Variable 'layer_weights:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.10620701,  0.12921634,  0.10339769],
       [-0.05376191,  0.08285449, -0.18392752]], dtype=float32)>
💡 Use case: Neural network weights that update during training



##  STEP 4: Reshaping Tensors (Very Important!)
🎯 Reshaping is crucial when connecting different layers in neural networks

In [18]:
# Start with a sample data tensor
original_data = tf.constant([[1, 2, 3, 4],
                            [5, 6, 7, 8]])
print(f"Original data {original_data.shape}:")
print(original_data)
print("This could represent: 2 samples, each with 4 features")
print()

Original data (2, 4):
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
This could represent: 2 samples, each with 4 features



In [19]:
# Flatten to 1D (common when going from CNN to dense layer)
print("Reshaping to different configurations:")
flattened = tf.reshape(original_data, (-1,))
print(f"Flattened to 1D {flattened.shape}: {flattened}")
print("💡 Use case: Flattening image data before dense layer")
print()

Reshaping to different configurations:
Flattened to 1D (8,): [1 2 3 4 5 6 7 8]
💡 Use case: Flattening image data before dense layer



In [20]:
# Reshape to column vector
column_vector = tf.reshape(original_data, (8, 1))
print(f"Reshaped to column vector {column_vector.shape}:")
print(column_vector)
print("💡 Use case: Preparing data for certain layer types")
print()

Reshaped to column vector (8, 1):
tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape=(8, 1), dtype=int32)
💡 Use case: Preparing data for certain layer types



In [21]:
# Reshape to 3D (adding batch dimension)
batched = tf.reshape(original_data, (1, 2, 4))
print(f"Reshaped to 3D with batch dimension {batched.shape}:")
print(batched)
print("💡 Use case: Adding batch dimension for neural network input")
print()

Reshaped to 3D with batch dimension (1, 2, 4):
tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]], shape=(1, 2, 4), dtype=int32)
💡 Use case: Adding batch dimension for neural network input



##  STEP 5: Working with Different Data Types
Understanding data types is important for memory efficiency and computation

In [22]:
# Integer tensor
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print(f"Integer tensor: {int_tensor} (dtype: {int_tensor.dtype})")

# Convert to float
float_tensor = tf.cast(int_tensor, tf.float32)
print(f"Converted to float: {float_tensor} (dtype: {float_tensor.dtype})")

# Boolean tensor
bool_tensor = tf.constant([True, False, True])
print(f"Boolean tensor: {bool_tensor} (dtype: {bool_tensor.dtype})")
print("💡 Use case: Creating masks for selective operations")
print()

Integer tensor: [1 2 3] (dtype: <dtype: 'int32'>)
Converted to float: [1. 2. 3.] (dtype: <dtype: 'float32'>)
Boolean tensor: [ True False  True] (dtype: <dtype: 'bool'>)
💡 Use case: Creating masks for selective operations



## ✅ VALIDATION & TESTING
Let's test your understanding with a practical example

In [23]:
print("🧠 SCENARIO: Processing a batch of 3 images for a neural network")
print()

# Simulate 3 grayscale images of size 4×4 pixels
batch_size = 3
height, width = 4, 4
input_batch = tf.random.uniform((batch_size, height, width), 0, 255, dtype=tf.float32)

print(f"Input batch shape: {input_batch.shape}")
print(f"This represents: {batch_size} images, each {height}×{width} pixels")
print()

# Flatten for dense layer (common operation)
flattened_batch = tf.reshape(input_batch, (batch_size, -1))
print(f"Flattened for dense layer: {flattened_batch.shape}")
print(f"This represents: {batch_size} samples, each with {height*width} features")
print()

# Check our work
expected_features = height * width
actual_features = flattened_batch.shape[1]
print(f"✅ Validation: Expected {expected_features} features, got {actual_features}")
print(f"✅ Shape check: {actual_features == expected_features}")
print()

🧠 SCENARIO: Processing a batch of 3 images for a neural network

Input batch shape: (3, 4, 4)
This represents: 3 images, each 4×4 pixels

Flattened for dense layer: (3, 16)
This represents: 3 samples, each with 16 features

✅ Validation: Expected 16 features, got 16
✅ Shape check: True



## 🔍 KEY TAKEAWAYS

1. **Tensors are the fundamental data structure** in neural networks
2. **Shape tells you the dimensions:** (batch_size, height, width, channels)
3. **Rank is the number of dimensions** (0D=scalar, 1D=vector, 2D=matrix, etc.)
4. **Reshaping is crucial** for connecting different types of layers
5. **Variables are tensors that can be trained** (weights and biases)
6. **Data type affects memory usage** and computation precision
7. **Always check tensor shapes** when debugging neural networks

### 🤔 QUESTIONS TO THINK ABOUT:
1)  How would you represent a batch of 32 color images (28×28 pixels)?

--> The NumPy array shape for a batch of 32 color images sized 28×28 is (32, 28, 28, 3), representing (batch_size, height, width, channels).

Example: images = np.zeros((32, 28, 28, 3)) for such a batch




2) What shape would the weights have for a layer with 128 inputs and 64 outputs?

--> The weight matrix for a dense layer with 128 inputs and 64 outputs has shape (128, 64).

This means every input feature is fully connected to every output neuron:

128 previous neurons × 64 output neurons = 8192 weights.


3)  Why do we need to flatten images before feeding them to dense layers?

-->  Dense layers require 1D vectors because every neuron expects one value per input.

Images start as 3D arrays (height × width × channels). Flattening (reshaping) turns this into a 1D array, allowing the dense layer to process every pixel individually.

Without flattening, the dense layer cannot correctly interpret the 2D+ structure of the image data; it needs a single vector per sample for matrix multiplication with the weights.

In [43]:
images = np.zeros((32, 28, 28, 3))

In [45]:
print(images)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0